// Run: node prisma/seed.js
const { PrismaClient } = require('../node_modules/.prisma/client')
const prisma = new PrismaClient()

const pizzaSize   = { id: 'pizza-size',   name: 'Choose Your Size',  required: true,  multiSelect: false, min: 1, max: 1, options: [{ id: 'size-9', name: '9" Personal', price: 0 }, { id: 'size-12', name: '12" Medium', price: 3.0 }, { id: 'size-15', name: '15" Large', price: 6.0 }, { id: 'size-18', name: '18" Extra Large', price: 9.0 }] }
const pizzaCrust  = { id: 'pizza-crust',  name: 'Choose Your Crust', required: true,  multiSelect: false, min: 1, max: 1, options: [{ id: 'crust-thin', name: 'Thin & Crispy', price: 0 }, { id: 'crust-classic', name: 'Classic Hand Tossed', price: 0 }, { id: 'crust-deep', name: 'Deep Pan', price: 0.5 }, { id: 'crust-stuffed', name: 'Stuffed Crust', price: 1.5 }] }
const pizzaSauce  = { id: 'pizza-sauce',  name: 'Choose Your Sauce', required: false, multiSelect: false, min: 0, max: 1, options: [{ id: 'sauce-tomato', name: 'Tomato', price: 0 }, { id: 'sauce-bbq', name: 'BBQ', price: 0 }, { id: 'sauce-garlic', name: 'Garlic', price: 0.5 }, { id: 'sauce-peri', name: 'Peri Peri', price: 0.5 }] }
const pizzaExtras = { id: 'pizza-extras', name: 'Add Extras',        required: false, multiSelect: true,  min: 0, max: 5, options: [{ id: 'extra-cheese', name: 'Extra Cheese', price: 1.0 }, { id: 'extra-jalapenos', name: 'Jalapeños', price: 0.5 }, { id: 'extra-olives', name: 'Black Olives', price: 0.5 }, { id: 'extra-mushrooms', name: 'Mushrooms', price: 0.5 }, { id: 'extra-pepperoni', name: 'Pepperoni', price: 1.0 }, { id: 'extra-sweetcorn', name: 'Sweetcorn', price: 0.5 }] }
const burgerExtras = { id: 'burger-extras', name: 'Add Extras', required: false, multiSelect: true, min: 0, max: 4, options: [{ id: 'b-extra-cheese', name: 'Extra Cheese', price: 0.5 }, { id: 'b-extra-bacon', name: 'Bacon', price: 1.0 }, { id: 'b-extra-jalapenos', name: 'Jalapeños', price: 0.5 }, { id: 'b-extra-sauce', name: 'Burger Sauce', price: 0 }] }
const drinkSize   = { id: 'drink-size',   name: 'Choose Size',       required: true,  multiSelect: false, min: 1, max: 1, options: [{ id: 'drink-can', name: 'Can (330ml)', price: 0 }, { id: 'drink-bottle', name: 'Bottle (1.5L)', price: 1.0 }] }

const pm = [pizzaSize, pizzaCrust, pizzaSauce, pizzaExtras]

function p(id, name, desc, price, img, cat, popular, mods, aller) {
  return { id, name, description: desc, price: Math.round(price * 100), image: img, category: cat, popular, available: true, modifiers: JSON.stringify(mods), allergens: JSON.stringify(aller) }
}

const CATEGORIES = [
  { id: 'pizza',        name: 'Pizza',               slug: 'pizza',        icon: '🍕', visible: true, order: 1  },
  { id: 'pizza-deals',  name: 'Pizza Crazy Deals',    slug: 'pizza-deals',  icon: '🤩', visible: true, order: 2  },
  { id: 'pizza-meal',   name: 'Pizza Meals',          slug: 'pizza-meal',   icon: '🍽️', visible: true, order: 3  },
  { id: 'burgers',      name: 'Burgers',              slug: 'burgers',      icon: '🍔', visible: true, order: 4  },
  { id: 'kebab',        name: 'Kebabs',               slug: 'kebab',        icon: '🥙', visible: true, order: 5  },
  { id: 'kebab-pizza',  name: 'Kebab Pizza Specials', slug: 'kebab-pizza',  icon: '🍕', visible: true, order: 6  },
  { id: 'wraps',        name: 'Wraps',                slug: 'wraps',        icon: '🌯', visible: true, order: 7  },
  { id: 'sides',        name: 'Sides',                slug: 'sides',        icon: '🍟', visible: true, order: 8  },
  { id: 'kids-meal',    name: 'Kids Meals',           slug: 'kids-meal',    icon: '👶', visible: true, order: 9  },
  { id: 'lunch-offers', name: 'Lunch Time Offers',    slug: 'lunch-offers', icon: '☀️', visible: true, order: 10 },
  { id: 'desserts',     name: 'Desserts',             slug: 'desserts',     icon: '🍰', visible: true, order: 11 },
  { id: 'dips',         name: 'Dips',                 slug: 'dips',         icon: '🫙', visible: true, order: 12 },
  { id: 'drinks',       name: 'Drinks',               slug: 'drinks',       icon: '🥤', visible: true, order: 13 },
]

const PRODUCTS = [
  p('american-hot',        'American Hot',                     'Spicy beef, jalapeños, red onions and green peppers on a tangy tomato sauce base with mozzarella cheese',        8.99,  '/images/Pizza/American hot.avif',                                                    'pizza',       true,  pm, ['Gluten','Dairy','Soya']),
  p('cheese-deluxe',       'Cheese Deluxe',                    "A cheese lover's dream — loaded with mozzarella, cheddar and parmesan on a classic tomato base",                 8.99,  '/images/Pizza/Cheese deluxe.avif',                                                   'pizza',       true,  pm, ['Gluten','Dairy']),
  p('chicken-tikka',       'Chicken Tikka',                    'Tender tikka chicken with peppers, red onions and a drizzle of mint yoghurt on a spiced tomato base',            9.99,  '/images/Pizza/Chicken tikka.avif',                                                   'pizza',       true,  pm, ['Gluten','Dairy','Mustard']),
  p('farm-house',          'Farm House',                       'Mushrooms, sweetcorn, peppers and red onions on a rich tomato sauce with mozzarella',                            8.99,  '/images/Pizza/Farm house.avif',                                                      'pizza',       false, pm, ['Gluten','Dairy']),
  p('hawaiian',            'Hawaiian',                         'Classic combination of ham and pineapple on a tomato sauce base with melted mozzarella cheese',                  8.99,  '/images/Pizza/Hawaiian.avif',                                                        'pizza',       false, pm, ['Gluten','Dairy']),
  p('hot-spicy',           'Hot & Spicy',                      'Spicy chicken, jalapeños, red chillies and peppers on a fiery tomato base with extra mozzarella',               9.99,  '/images/Pizza/Hot & spicy.avif',                                                     'pizza',       true,  pm, ['Gluten','Dairy']),
  p('margherita',          'Margherita',                       'The Italian classic — fresh tomato sauce with mozzarella and a hint of basil',                                   7.99,  '/images/Pizza/Margherita.avif',                                                      'pizza',       false, pm, ['Gluten','Dairy']),
  p('meat-feast',          'Meat Feast',                       'Loaded with pepperoni, beef mince, chicken, ham and sausage on a rich tomato base',                             10.99, '/images/Pizza/Meat feast.avif',                                                      'pizza',       true,  pm, ['Gluten','Dairy']),
  p('new-yorker',          'New Yorker',                       'Big New York slices packed with pepperoni, beef and green peppers on a classic tomato base',                    10.99, '/images/Pizza/New yorker.avif',                                                      'pizza',       false, pm, ['Gluten','Dairy']),
  p('pepperoni-feast',     'Pepperoni Feast',                  'Double pepperoni layered on a zesty tomato sauce with mozzarella — a true classic',                             9.99,  '/images/Pizza/Pepperoni feast.avif',                                                 'pizza',       true,  pm, ['Gluten','Dairy']),
  p('pepperoni-sizzler',   'Pepperoni Sizzler',                'Sizzling pepperoni with jalapeños and extra cheese on a spiced tomato sauce',                                  10.99, '/images/Pizza/Pepperoni sizzler pizza.avif',                                         'pizza',       false, pm, ['Gluten','Dairy']),
  p('seafood-special',     'Seafood Special',                  'Prawns, tuna and sweetcorn on a creamy garlic base with mozzarella cheese',                                    11.99, '/images/Pizza/Seafood special.avif',                                                 'pizza',       false, pm, ['Gluten','Dairy','Fish','Crustaceans']),
  p('tandoori-chicken',    'Tandoori Chicken',                 'Marinated tandoori chicken with peppers and onions on a spiced tomato base',                                    9.99,  '/images/Pizza/Tandoori chicken.avif',                                                'pizza',       false, pm, ['Gluten','Dairy','Mustard']),
  p('texas-bbq',           'Texas BBQ',                        'Smoky BBQ chicken, beef and onions on a rich BBQ sauce base with mozzarella',                                  10.99, '/images/Pizza/Texas bbq.avif',                                                       'pizza',       true,  pm, ['Gluten','Dairy']),
  p('tuna-delight',        'Tuna Delight',                     'Tuna, sweetcorn and red onions on a creamy tomato base with mozzarella',                                       9.99,  '/images/Pizza/Tuna delight.avif',                                                    'pizza',       false, pm, ['Gluten','Dairy','Fish']),
  p('veggie-sizzler',      'Veggie Sizzler Hot',               'Roasted peppers, mushrooms, jalapeños and sweetcorn on a spicy tomato base — vegetarian friendly',              8.99,  '/images/Pizza/Veggie sizzler hot.avif',                                              'pizza',       false, pm, ['Gluten','Dairy']),
  p('veggie-special',      'Veggie Special',                   'Mushrooms, peppers, red onions, sweetcorn and olives on a classic tomato base',                                 8.99,  '/images/Pizza/Veggie special.avif',                                                  'pizza',       false, pm, ['Gluten','Dairy']),
  p('deal-2x9',            'Any 2 x 9" Pizzas',                'Choose any 2 personal 9-inch pizzas from our full menu. Mix and match your favourites!',                        14.99, '/images/Pizza Crazy deals/Any 2 x 9 inch pizza.avif',                                'pizza-deals', true,  [], []),
  p('deal-2x12',           'Any 2 x 12" Pizzas',               'Choose any 2 medium 12-inch pizzas from our full menu. Perfect for sharing!',                                   19.99, '/images/Pizza Crazy deals/Any 2 x 12 inch pizza.avif',                               'pizza-deals', true,  [], []),
  p('deal-2x15',           'Any 2 x 15" Pizzas',               'Choose any 2 large 15-inch pizzas from our full menu. Great value for hungry families!',                        24.99, '/images/Pizza Crazy deals/Any 2 x 15 inch pizza.avif',                               'pizza-deals', false, [], []),
  p('deal-2x18',           'Any 2 x 18" Pizzas',               'Choose any 2 extra-large 18-inch pizzas. The ultimate pizza feast for the whole family!',                       29.99, '/images/Pizza Crazy deals/Any 2 x 18 inch pizza.avif',                               'pizza-deals', false, [], []),
  p('meal-deal-1',         'Meal Deal 1',                      '9" pizza + side of fries + regular drink. A complete meal at an unbeatable price',                              12.99, '/images/Pizza Meal/Meal deal 1.avif',                                                'pizza-meal',  true,  [], []),
  p('meal-deal-2',         'Meal Deal 2',                      '12" pizza + 2 sides + 2 drinks. Perfect for couples or sharing with a friend',                                  17.99, '/images/Pizza Meal/Meal deal 2.avif',                                                'pizza-meal',  false, [], []),
  p('big-meal-deal',       'Big Meal Deal',                    "15\" pizza + 3 sides + 3 drinks. A hearty meal that's perfect for the family",                                  24.99, '/images/Pizza Meal/Big meal deal.avif',                                               'pizza-meal',  true,  [], []),
  p('pizza-combo-family',  'Pizza Combo Family Deal',          '18" pizza + 4 sides + 4 drinks. The ultimate family feast for everyone to enjoy!',                              34.99, '/images/Pizza Meal/Pizza combo family deal.avif',                                    'pizza-meal',  false, [], []),
  p('party-pack',          'Party Pack',                       '2 x 15" pizzas + garlic bread + 6 dips + 6 drinks. Feed the whole party!',                                     49.99, '/images/Pizza Meal/Party pack.avif',                                                 'pizza-meal',  false, [], []),
  p('ice-cream-lovers',    'Ice Cream Lovers',                 '12" pizza + 2 ice cream desserts of your choice.',                                                              18.99, '/images/Pizza Meal/Ice cream lovers.avif',                                           'pizza-meal',  false, [], []),
  p('bbq-smash-burger',    'BBQ Smash Burger',                 'Double smash patties with crispy bacon, BBQ sauce, cheese and pickles in a toasted brioche bun',                8.99,  '/images/Burgers/Bbq smash burger.avif',                                              'burgers',     true,  [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('cheeseburger',        'Cheeseburger',                     'Classic beef patty with melted cheese, lettuce, tomato, onion and burger sauce',                                5.99,  '/images/Burgers/Cheeseburger.avif',                                                  'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('chicken-fillet-burger','Chicken Fillet Burger',           'Crispy golden chicken fillet with lettuce, mayo and pickles in a soft bun',                                     6.99,  '/images/Burgers/Chicken fillet burger.avif',                                         'burgers',     true,  [burgerExtras], ['Gluten','Dairy','Egg','Sesame','Mustard']),
  p('classic-smash-burger','Classic Smash Burger',             'Smashed beef patty with cheese, caramelised onions and signature sauce in a toasted bun',                      7.99,  '/images/Burgers/Classic smash burger.avif',                                          'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('double-cheeseburger', 'Double Cheeseburger',              'Two beef patties, double cheese, lettuce, tomato, onion and burger sauce — double the deliciousness!',          7.99,  '/images/Burgers/Double cheeseburger.avif',                                           'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('half-pounder',        'Half Pounder Burger',              'A massive half-pound beef patty with lettuce, tomato, cheese and our special sauce',                           10.99, '/images/Burgers/Half pounder burger.avif',                                           'burgers',     true,  [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('quarter-pounder',     'Quarter Pounder Burger',           'A juicy quarter-pound beef patty with all the classic burger toppings',                                         7.99,  '/images/Burgers/Quarter pounder burger.avif',                                        'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame']),
  p('spicy-chicken-fillet','Spicy Chicken Fillet Burger',      'Crispy spiced chicken fillet with peri peri mayo, fresh chillies and pickles in a soft bun',                   7.99,  '/images/Burgers/Spicy chicken fillet burger.avif',                                   'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame','Mustard']),
  p('veggie-burger',       'Veggie Burger',                    'A flavourful plant-based patty with lettuce, tomato, cheese and burger sauce',                                  6.99,  '/images/Burgers/Veggie burger.avif',                                                 'burgers',     false, [burgerExtras], ['Gluten','Dairy','Egg','Sesame','Soya']),
  p('chicken-kebab',       'Chicken Kebab',                    'Marinated grilled chicken served with salad, garlic sauce and pitta bread',                                     8.99,  '/images/Kebab/Chicken Kebab.avif',                                                   'kebab',       true,  [], ['Gluten','Dairy','Sesame']),
  p('lamb-kebab',          'Lamb Doner Kebab',                 'Tender sliced lamb doner with fresh salad, chilli sauce and pitta bread',                                       8.99,  '/images/Kebab/Lamb kebab.avif',                                                      'kebab',       true,  [], ['Gluten','Dairy','Sesame']),
  p('kebab-pizza-special', 'Kebab Pizza Special',              'A unique fusion of doner kebab meat on a pizza base with garlic sauce and mozzarella',                         11.99, '/images/Kebab Pizza specials/Kebab Pizza Specials.avif',                             'kebab-pizza', true,  [pizzaSize, pizzaCrust], ['Gluten','Dairy','Sesame']),
  p('doner-pizza',         'Lamb/Chicken/Mixed Doner Kebab Pizza','Your choice of lamb, chicken or mixed doner on a pizza base with salad sauce and cheese',                   12.99, '/images/Kebab Pizza specials/Lamb or chicken or mixed meat doner kebab pizza.avif', 'kebab-pizza', false, [pizzaSize, pizzaCrust], ['Gluten','Dairy','Sesame']),
  p('chicken-doner-wrap',  'Chicken Doner Wrap',               'Grilled chicken doner with fresh salad, garlic mayo and chilli sauce in a warm tortilla',                      6.99,  '/images/Wraps/Chicken doner wrap.avif',                                              'wraps',       true,  [], ['Gluten','Dairy','Sesame','Egg']),
  p('lamb-doner-wrap',     'Lamb Doner Wrap',                  'Tender lamb doner with crisp salad, garlic mayo and chilli sauce wrapped in a soft tortilla',                   6.99,  '/images/Wraps/Lamb doner wrap.avif',                                                 'wraps',       false, [], ['Gluten','Dairy','Sesame','Egg']),
  p('mixed-doner-wrap',    'Mixed Doner Wrap',                 'A mix of chicken and lamb doner with salad, garlic mayo and chilli sauce in a warm tortilla',                   7.49,  '/images/Wraps/Mixed doner wrap.avif',                                                'wraps',       false, [], ['Gluten','Dairy','Sesame','Egg']),
  p('mozzarella-balls',    '10 Mozzarella Balls',              'Crispy golden mozzarella balls with a gooey melted cheese centre, served with dipping sauce',                   4.99,  '/images/Sides/10 mozzarella balls.avif',                                             'sides',       true,  [], ['Gluten','Dairy','Egg']),
  p('mozzarella-sticks',   '10 Mozzarella Sticks',             'Classic mozzarella sticks breaded to perfection, served with marinara dipping sauce',                          4.99,  '/images/Sides/10 mozzarella sticks.avif',                                            'sides',       false, [], ['Gluten','Dairy','Egg']),
  p('chicken-nuggets',     '10 Pcs Chicken Nuggets',           'Tender chicken nuggets with a crispy golden coating, served with your choice of dipping sauce',                4.49,  '/images/Sides/10 pcs chicken nuggets.avif',                                          'sides',       true,  [], ['Gluten','Dairy','Egg']),
  p('hot-chicken-wings',   '10 Pcs Hot Chicken Wings',         'Fiery hot chicken wings marinated in our special spice blend, served with cooling dip',                        5.99,  '/images/Sides/10 pcs hot chicken wings.avif',                                        'sides',       false, [], ['Gluten','Dairy']),
  p('onion-rings',         '10 Pcs Onion Rings',               'Beer-battered crispy onion rings, perfectly golden and served with garlic mayo',                               3.99,  '/images/Sides/10 pcs onion rings.avif',                                              'sides',       false, [], ['Gluten','Dairy','Egg']),
  p('mutton-rolls',        '3 Pcs Mutton Rolls',               'Spiced mutton mince wrapped in crispy pastry, deep fried to golden perfection',                                3.99,  '/images/Sides/3 pcs mutton rolls.avif',                                              'sides',       false, [], ['Gluten','Dairy']),
  p('veg-rolls',           '3 Pcs Veg Rolls',                  'Mixed vegetable rolls wrapped in crispy pastry — a tasty vegetarian option',                                    3.49,  '/images/Sides/3 pcs veg rolls.avif',                                                 'sides',       false, [], ['Gluten','Dairy']),
  p('garlic-bread',        '4 Pcs Garlic Bread',               'Warm baguette slices brushed with garlic butter, toasted to perfection',                                       2.99,  '/images/Sides/4 pcs garlic bread.avif',                                              'sides',       true,  [], ['Gluten','Dairy']),
  p('meat-samosa',         '4 Pcs Meat Samosa',                'Crispy pastry triangles filled with spiced minced meat and vegetables',                                        3.49,  '/images/Sides/4 pcs meat samosa.avif',                                               'sides',       false, [], ['Gluten','Dairy']),
  p('veg-samosa',          '5 Pcs Vegetable Samosa',           'Light and crispy samosas filled with spiced potatoes, peas and vegetables',                                     3.49,  '/images/Sides/5 pcs vegetable samosa.avif',                                          'sides',       false, [], ['Gluten','Dairy']),
  p('bbq-wings',           '6 Pcs BBQ Chicken Wings',          'Smoky BBQ glazed chicken wings, sticky and finger-licking good',                                                4.99,  '/images/Sides/6 pcs bbq chicken wings.avif',                                         'sides',       false, [], ['Gluten','Dairy']),
  p('chicken-dippers',     '6 Pcs Chicken Dippers',            'Crispy breaded chicken strips, ideal for dipping in your favourite sauce',                                      4.99,  '/images/Sides/6 pcs chicken dippers.avif',                                           'sides',       false, [], ['Gluten','Dairy','Egg']),
  p('cheesy-chips',        'Cheesy Chips',                     'Golden fries topped with melted cheese sauce — irresistibly good',                                              3.49,  '/images/Sides/Cheesy chips.avif',                                                    'sides',       true,  [], ['Gluten','Dairy']),
  p('chicken-popcorn',     'Chicken Popcorn',                  'Bite-sized crispy chicken pieces — perfect for snacking or sharing',                                            3.99,  '/images/Sides/Chicken popcorn.avif',                                                 'sides',       false, [], ['Gluten','Dairy','Egg']),
  p('french-fries',        'French Fries',                     'Classic crispy golden fries, seasoned with a pinch of salt',                                                    2.49,  '/images/Sides/French fries.avif',                                                    'sides',       true,  [], ['Gluten']),
  p('garlic-bread-cheese', 'Garlic Bread with Cheese',         'Warm garlic bread topped with melted mozzarella cheese',                                                       3.49,  '/images/Sides/Garlic bread with cheese.avif',                                        'sides',       false, [], ['Gluten','Dairy']),
  p('potato-wedges',       'Regular Potato Wedges',            'Chunky seasoned potato wedges, crispy on the outside and fluffy in the middle',                                3.49,  '/images/Sides/Regular potato wedges.avif',                                           'sides',       false, [], ['Gluten']),
  p('supreme-salad',       'Supreme Salads',                   'Fresh mixed salad with lettuce, tomatoes, cucumber, onions and dressing',                                      3.99,  '/images/Sides/Supreme salads.avif',                                                  'sides',       false, [], ['Mustard']),
  p('kids-cheeseburger',   'Kids Cheese Burger Meal',          'A smaller cheeseburger with kids fries and a drink — perfect for little ones',                                  5.99,  '/images/Kids meal/Cheese burger meal.avif',                                          'kids-meal',   false, [], ['Gluten','Dairy','Egg','Sesame']),
  p('kids-chicken-fillet', 'Kids Chicken Fillet Burger Meal',  'Mini chicken fillet burger with kids fries and a soft drink',                                                   5.99,  '/images/Kids meal/Chicken fillet burger meal.avif',                                  'kids-meal',   false, [], ['Gluten','Dairy','Egg','Sesame','Mustard']),
  p('kids-nuggets',        'Kids Chicken Nuggets Meal',        '6 chicken nuggets with kids fries and a choice of drink',                                                       5.49,  '/images/Kids meal/Chicken nuggets meal.avif',                                        'kids-meal',   true,  [], ['Gluten','Dairy','Egg']),
  p('kids-popcorn',        'Kids Chicken Popcorn Meal',        'Crispy chicken popcorn with kids fries and a soft drink',                                                       5.49,  '/images/Kids meal/Chicken popcorn meal.avif',                                        'kids-meal',   false, [], ['Gluten','Dairy','Egg']),
  p('lunch-kebab',         'Any Kebab Meal',                   'Choice of chicken or lamb kebab + fries + regular drink. Available Mon-Fri 11am-4pm',                           9.99,  '/images/Lunch TIme Offers/Any kebab meal.avif',                                      'lunch-offers',false, [], []),
  p('lunch-large-pizza',   'Any Large Pizza Meal',             '12" pizza + fries + regular drink. Available Mon-Fri 11am-4pm',                                                 14.99, '/images/Lunch TIme Offers/Any large pizza meal.avif',                                'lunch-offers',true,  [], []),
  p('lunch-medium-pizza',  'Any Medium Pizza Meal',            '9" pizza + fries + regular drink. Available Mon-Fri 11am-4pm',                                                  10.99, '/images/Lunch TIme Offers/Any medium pizza meal.avif',                               'lunch-offers',false, [], []),
  p('lunch-cheeseburger',  'Cheese Burger Meal',               'Cheeseburger + fries + regular drink. Available Mon-Fri 11am-4pm',                                              7.99,  '/images/Lunch TIme Offers/Cheese burger meal.avif',                                  'lunch-offers',false, [], []),
  p('lunch-wrap',          'Chicken or Lamb Wrap Meal',        'Chicken or lamb wrap + fries + regular drink. Available Mon-Fri 11am-4pm',                                      8.99,  '/images/Lunch TIme Offers/Chicken or lamb wrap meal.avif',                          'lunch-offers',false, [], []),
  p('lunch-double-cheese', 'Double Cheese Burger Meal',        'Double cheeseburger + fries + regular drink. Available Mon-Fri 11am-4pm',                                       9.49,  '/images/Lunch TIme Offers/Double cheese burger meal.avif',                          'lunch-offers',false, [], []),
  p('ben-jerrys',          "Ben & Jerry's Ice Cream",          "America's most loved ice cream — choose from a range of indulgent flavours",                                    4.99,  "/images/Dessert/Ben & jerry's ice cream.avif",                                       'desserts',    true,  [], ['Dairy','Egg','Soya']),
  p('carrot-cake',         'Carrot Cake',                      'Moist homemade carrot cake with cream cheese frosting — a classic treat',                                       3.49,  '/images/Dessert/Carrot cake.avif',                                                   'desserts',    false, [], ['Gluten','Dairy','Egg','Nuts']),
  p('chocolate-fudge-cake','Chocolate Fudge Cake',             'Rich and decadent chocolate fudge cake with chocolate ganache — pure indulgence',                               3.49,  '/images/Dessert/Chocolate fudge cake.avif',                                          'desserts',    true,  [], ['Gluten','Dairy','Egg','Soya']),
  p('haagen-dazs',         'Häagen-Dazs Ice Cream',           'Premium luxury ice cream in a variety of classic and indulgent flavours',                                       4.99,  '/images/Dessert/Haagen-dazs ice cream.avif',                                         'desserts',    false, [], ['Dairy','Egg']),
  p('strawberry-cheesecake','Strawberry Cheesecake',           'Creamy New York style cheesecake with a fresh strawberry topping on a biscuit base',                            3.99,  '/images/Dessert/Strawberry cheese cake.avif',                                        'desserts',    false, [], ['Gluten','Dairy','Egg']),
  p('bbq-dip',             'BBQ Dip',                          'Smoky and sweet BBQ dipping sauce — pairs perfectly with wings and dippers',                                    0.99,  '/images/Dips/Bbq dip.avif',                                                         'dips',        false, [], []),
  p('garlic-mayo',         'Garlic Mayo',                      'Creamy garlic mayonnaise — the perfect dip for fries and kebabs',                                               0.99,  '/images/Dips/Garlic mayo.avif',                                                      'dips',        true,  [], ['Egg','Mustard']),
  p('sour-cream',          'Sour Cream',                       'Cool and tangy sour cream dip — great with wedges and nachos',                                                  0.99,  '/images/Dips/Sour cream.avif',                                                       'dips',        false, [], ['Dairy']),
  p('spicy-mayo',          'Spicy Mayo',                       'Creamy mayonnaise with a fiery chilli kick — not for the faint hearted!',                                       0.99,  '/images/Dips/Spicy mayo.avif',                                                       'dips',        false, [], ['Egg','Mustard']),
  p('coke',                'Coca-Cola',                        'The classic taste of Coca-Cola, ice cold and refreshing',                                                       1.49,  '/images/Drinks/Coke.avif',                                                           'drinks',      true,  [drinkSize], []),
  p('diet-coke',           'Diet Coke',                        'All the great Coca-Cola taste with no sugar',                                                                   1.49,  '/images/Drinks/Diet coke.avif',                                                      'drinks',      false, [drinkSize], []),
  p('pepsi',               'Pepsi',                            'Ice cold Pepsi — the taste that makes you smile',                                                               1.49,  '/images/Drinks/Pepsi.avif',                                                          'drinks',      false, [drinkSize], []),
  p('pepsi-max',           'Pepsi Max',                        'Maximum Pepsi taste with zero sugar',                                                                           1.49,  '/images/Drinks/Pepsi max.avif',                                                      'drinks',      false, [drinkSize], []),
  p('7up',                 '7UP',                              'Crisp, clean lemon-lime flavour — light and refreshing',                                                        1.49,  '/images/Drinks/7 up.avif',                                                           'drinks',      false, [drinkSize], []),
  p('tango-orange',        'Tango Orange',                     'Intensely fruity orange flavour fizzy drink',                                                                   1.49,  '/images/Drinks/Tango orange.avif',                                                   'drinks',      false, [drinkSize], []),
  p('mirinda',             'Mirinda',                          'Sweet and fruity orange soft drink',                                                                            1.49,  '/images/Drinks/Mirinda.avif',                                                        'drinks',      false, [drinkSize], []),
  p('rubicon-mango',       'Rubicon Mango',                    'Exotic mango fruit drink — a tropical delight',                                                                 1.49,  '/images/Drinks/Rubicon mango.avif',                                                  'drinks',      true,  [], []),
  p('rubicon-guava',       'Rubicon Guava',                    'Refreshing guava fruit drink with a tropical twist',                                                            1.49,  '/images/Drinks/Rubicon guava.avif',                                                  'drinks',      false, [], []),
  p('rubicon-lychee',      'Rubicon Lychee',                   'Delicate and sweet lychee fruit drink',                                                                         1.49,  '/images/Drinks/Rubicon lychee.avif',                                                 'drinks',      false, [], []),
  p('rubicon-passion',     'Rubicon Passion',                  'Tangy passionfruit drink full of tropical flavour',                                                             1.49,  '/images/Drinks/Rubicon passion.avif',                                                'drinks',      false, [], []),
  p('coke-bottle',         'Coca-Cola Bottle (1.5L)',           'Large bottle of ice cold Coca-Cola — perfect for sharing',                                                      2.49,  '/images/Drinks/Coke bottle.avif',                                                    'drinks',      false, [], []),
  p('pepsi-max-bottle',    'Pepsi Max Bottle (1.5L)',           'Large bottle of Pepsi Max — zero sugar, maximum taste',                                                         2.49,  '/images/Drinks/Pepsi max bottle.avif',                                               'drinks',      false, [], []),
]

async function main() {
  let catsSeeded = 0, prodsSeeded = 0

  for (const cat of CATEGORIES) {
    const exists = await prisma.category.findUnique({ where: { id: cat.id } })
    if (!exists) { await prisma.category.create({ data: cat }); catsSeeded++ }
  }

  for (const product of PRODUCTS) {
    const exists = await prisma.product.findUnique({ where: { id: product.id } })
    if (!exists) { await prisma.product.create({ data: product }); prodsSeeded++ }
  }

  console.log(`✅ Seed complete — categories: ${catsSeeded} added, products: ${prodsSeeded} added`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
